### ISSUE TITLE
Hotkey repetition?

### ISSUE THREAD

**Issue by LGUG2Z** [dnlmlr/windows-hotkeys#1]
I use this crate as a dependency of [`whkd`](https://github.com/LGUG2Z/whkd), which is pretty much just a thin wrapper around this with an sxkhd-esque DSL on top.

A user opened [this issue](https://github.com/LGUG2Z/whkd/issues/27) on the `whkd` repo inquiring about the possibility of hotkey repetitions on hold.

I poked around in the source code and removed `MOD_NOREPEAT` from [here](https://github.com/dnlmlr/windows-hotkeys/blob/4316fa1424753be49143e430c5ad33069b363575/src/singlethreaded.rs#L77) which was able to produce the desired effect.

Is there any interest in integrating a change to this library that could make this behaviour configurable for callers?

**Comment by dnlmlr** [comment]
Hey! Making it configurable definitely sounds like a good idea. I decided to use the no repeating property originally, since I myself didn't want the repeating triggers in my own application.

When I have some time (end of this week) I'll implement this as a configurable option. Feel free to tag me if you happen to look at this at some point later and I didn't do anything up to that point

**Comment by dnlmlr** [comment]
Ok I just implemented it. 
It's released as [Version 0.2.1](https://crates.io/crates/windows-hotkeys/0.2.1) on crates.io, but the docs will probably take a while to build. Of course it's also in the [Github release](https://github.com/dnlmlr/windows-hotkeys/releases/tag/v0.2.1) and you can take a look at [the new example](https://github.com/dnlmlr/windows-hotkeys/blob/c11150cb091a82988792f55960a5151e61b8aa98/examples/no_repeat.rs) to see how it can be used.

Let me know if this works for you and feel free to close the issue if you think it is resolved. I believe this should make it pretty easy to resolve [your issue](https://github.com/LGUG2Z/whkd/issues/27).
Depending on your implementation, you could also utilize the `ModKey::NoRepeat` in the config file to enable / disable the behavior for certain combinations

**Comment by LGUG2Z** [comment]
Thank you! This is perfect, I was able to integrate the option introduced in the new version [very easily](https://www.youtube.com/watch?v=kjw5SJhyPCk)!
